// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: appointment.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//change service to services because of conflicts with the reserved word
type Appointment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date     string        `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Employee []*Employee   `protobuf:"bytes,3,rep,name=employee,proto3" json:"employee,omitempty"`
	Services []*Service    `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	Place    string        `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty"`
	Office   *BranchOffice `protobuf:"bytes,6,opt,name=office,proto3" json:"office,omitempty"`
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appointment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Appointment) GetEmployee() []*Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

func (x *Appointment) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Appointment) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *Appointment) GetOffice() *BranchOffice {
	if x != nil {
		return x.Office
	}
	return nil
}

type CreateAppointmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date     string      `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Employee []*Employee `protobuf:"bytes,2,rep,name=employee,proto3" json:"employee,omitempty"`
	Services []*Service  `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Place    string      `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty"`
	Client   string      `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *CreateAppointmentReq) Reset() {
	*x = CreateAppointmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appointment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppointmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentReq) ProtoMessage() {}

func (x *CreateAppointmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentReq.ProtoReflect.Descriptor instead.
func (*CreateAppointmentReq) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateAppointmentReq) GetEmployee() []*Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

func (x *CreateAppointmentReq) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *CreateAppointmentReq) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *CreateAppointmentReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type AppointmentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sucess    bool                 `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Id        string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *AppointmentRes) Reset() {
	*x = AppointmentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appointment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentRes) ProtoMessage() {}

func (x *AppointmentRes) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentRes.ProtoReflect.Descriptor instead.
func (*AppointmentRes) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *AppointmentRes) GetSucess() bool {
	if x != nil {
		return x.Sucess
	}
	return false
}

func (x *AppointmentRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppointmentRes) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAppointmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string        `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Office *BranchOffice `protobuf:"bytes,2,opt,name=office,proto3" json:"office,omitempty"`
}

func (x *GetAppointmentReq) Reset() {
	*x = GetAppointmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appointment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentReq) ProtoMessage() {}

func (x *GetAppointmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentReq.ProtoReflect.Descriptor instead.
func (*GetAppointmentReq) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetAppointmentReq) GetOffice() *BranchOffice {
	if x != nil {
		return x.Office
	}
	return nil
}

var File_appointment_proto protoreflect.FileDescriptor

var file_appointment_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x5f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a,
	0x0b, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0x73, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x51, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x28, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x65, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x32, 0x94, 0x01, 0x0a, 0x11, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d,
	0x61, 0x75, 0x2d, 0x4d, 0x52, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appointment_proto_rawDescOnce sync.Once
	file_appointment_proto_rawDescData = file_appointment_proto_rawDesc
)

func file_appointment_proto_rawDescGZIP() []byte {
	file_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(file_appointment_proto_rawDescData)
	})
	return file_appointment_proto_rawDescData
}

var file_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_appointment_proto_goTypes = []interface{}{
	(*Appointment)(nil),          // 0: pb.Appointment
	(*CreateAppointmentReq)(nil), // 1: pb.CreateAppointmentReq
	(*AppointmentRes)(nil),       // 2: pb.AppointmentRes
	(*GetAppointmentReq)(nil),    // 3: pb.GetAppointmentReq
	(*Employee)(nil),             // 4: pb.Employee
	(*Service)(nil),              // 5: pb.Service
	(*BranchOffice)(nil),         // 6: pb.BranchOffice
	(*timestamp.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_appointment_proto_depIdxs = []int32{
	4, // 0: pb.Appointment.employee:type_name -> pb.Employee
	5, // 1: pb.Appointment.services:type_name -> pb.Service
	6, // 2: pb.Appointment.office:type_name -> pb.BranchOffice
	4, // 3: pb.CreateAppointmentReq.employee:type_name -> pb.Employee
	5, // 4: pb.CreateAppointmentReq.services:type_name -> pb.Service
	7, // 5: pb.AppointmentRes.created_at:type_name -> google.protobuf.Timestamp
	6, // 6: pb.GetAppointmentReq.office:type_name -> pb.BranchOffice
	3, // 7: pb.AppointmenService.GetAppointment:input_type -> pb.GetAppointmentReq
	1, // 8: pb.AppointmenService.CreateAppointment:input_type -> pb.CreateAppointmentReq
	0, // 9: pb.AppointmenService.GetAppointment:output_type -> pb.Appointment
	2, // 10: pb.AppointmenService.CreateAppointment:output_type -> pb.AppointmentRes
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_appointment_proto_init() }
func file_appointment_proto_init() {
	if File_appointment_proto != nil {
		return
	}
	file_employee_proto_init()
	file_branch_office_proto_init()
	file_service_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_appointment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Appointment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appointment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppointmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appointment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appointment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appointment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_proto_depIdxs,
		MessageInfos:      file_appointment_proto_msgTypes,
	}.Build()
	File_appointment_proto = out.File
	file_appointment_proto_rawDesc = nil
	file_appointment_proto_goTypes = nil
	file_appointment_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppointmenServiceClient is the client API for AppointmenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppointmenServiceClient interface {
	GetAppointment(ctx context.Context, in *GetAppointmentReq, opts ...grpc.CallOption) (*Appointment, error)
	CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*AppointmentRes, error)
}

type appointmenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppointmenServiceClient(cc grpc.ClientConnInterface) AppointmenServiceClient {
	return &appointmenServiceClient{cc}
}

func (c *appointmenServiceClient) GetAppointment(ctx context.Context, in *GetAppointmentReq, opts ...grpc.CallOption) (*Appointment, error) {
	out := new(Appointment)
	err := c.cc.Invoke(ctx, "/pb.AppointmenService/GetAppointment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appointmenServiceClient) CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*AppointmentRes, error) {
	out := new(AppointmentRes)
	err := c.cc.Invoke(ctx, "/pb.AppointmenService/CreateAppointment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppointmenServiceServer is the server API for AppointmenService service.
type AppointmenServiceServer interface {
	GetAppointment(context.Context, *GetAppointmentReq) (*Appointment, error)
	CreateAppointment(context.Context, *CreateAppointmentReq) (*AppointmentRes, error)
}

// UnimplementedAppointmenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAppointmenServiceServer struct {
}

func (*UnimplementedAppointmenServiceServer) GetAppointment(context.Context, *GetAppointmentReq) (*Appointment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointment not implemented")
}
func (*UnimplementedAppointmenServiceServer) CreateAppointment(context.Context, *CreateAppointmentReq) (*AppointmentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppointment not implemented")
}

func RegisterAppointmenServiceServer(s *grpc.Server, srv AppointmenServiceServer) {
	s.RegisterService(&_AppointmenService_serviceDesc, srv)
}

func _AppointmenService_GetAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmenServiceServer).GetAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppointmenService/GetAppointment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmenServiceServer).GetAppointment(ctx, req.(*GetAppointmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppointmenService_CreateAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppointmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmenServiceServer).CreateAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppointmenService/CreateAppointment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmenServiceServer).CreateAppointment(ctx, req.(*CreateAppointmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppointmenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AppointmenService",
	HandlerType: (*AppointmenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppointment",
			Handler:    _AppointmenService_GetAppointment_Handler,
		},
		{
			MethodName: "CreateAppointment",
			Handler:    _AppointmenService_CreateAppointment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appointment.proto",
}
