// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: bussines.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Bussines struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Categories []string        `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Offices    []*BranchOffice `protobuf:"bytes,4,rep,name=offices,proto3" json:"offices,omitempty"`
	Services   []*Service      `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	Products   []*Product      `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	Warehouse  []*Product      `protobuf:"bytes,7,rep,name=warehouse,proto3" json:"warehouse,omitempty"`
	Employees  []*Employee     `protobuf:"bytes,8,rep,name=employees,proto3" json:"employees,omitempty"`
}

func (x *Bussines) Reset() {
	*x = Bussines{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bussines_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bussines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bussines) ProtoMessage() {}

func (x *Bussines) ProtoReflect() protoreflect.Message {
	mi := &file_bussines_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bussines.ProtoReflect.Descriptor instead.
func (*Bussines) Descriptor() ([]byte, []int) {
	return file_bussines_proto_rawDescGZIP(), []int{0}
}

func (x *Bussines) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bussines) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bussines) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Bussines) GetOffices() []*BranchOffice {
	if x != nil {
		return x.Offices
	}
	return nil
}

func (x *Bussines) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Bussines) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Bussines) GetWarehouse() []*Product {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

func (x *Bussines) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type CreateBusssinesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Categories []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *CreateBusssinesReq) Reset() {
	*x = CreateBusssinesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bussines_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBusssinesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusssinesReq) ProtoMessage() {}

func (x *CreateBusssinesReq) ProtoReflect() protoreflect.Message {
	mi := &file_bussines_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusssinesReq.ProtoReflect.Descriptor instead.
func (*CreateBusssinesReq) Descriptor() ([]byte, []int) {
	return file_bussines_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBusssinesReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBusssinesReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type BussinesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succes bool   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Status:
	//	*BussinesRes_CreatedAt
	Status isBussinesRes_Status `protobuf_oneof:"status"`
}

func (x *BussinesRes) Reset() {
	*x = BussinesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bussines_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BussinesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BussinesRes) ProtoMessage() {}

func (x *BussinesRes) ProtoReflect() protoreflect.Message {
	mi := &file_bussines_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BussinesRes.ProtoReflect.Descriptor instead.
func (*BussinesRes) Descriptor() ([]byte, []int) {
	return file_bussines_proto_rawDescGZIP(), []int{2}
}

func (x *BussinesRes) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

func (x *BussinesRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *BussinesRes) GetStatus() isBussinesRes_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *BussinesRes) GetCreatedAt() *timestamp.Timestamp {
	if x, ok := x.GetStatus().(*BussinesRes_CreatedAt); ok {
		return x.CreatedAt
	}
	return nil
}

type isBussinesRes_Status interface {
	isBussinesRes_Status()
}

type BussinesRes_CreatedAt struct {
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof"`
}

func (*BussinesRes_CreatedAt) isBussinesRes_Status() {}

var File_bussines_proto protoreflect.FileDescriptor

var file_bussines_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x6f, 0x66,
	0x66, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x08, 0x42, 0x75, 0x73,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x6f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x07, 0x6f, 0x66,
	0x66, 0x69, 0x63, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x27,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x09, 0x77, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x09, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x22, 0x48,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x73, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x7c, 0x0a, 0x0b, 0x42, 0x75, 0x73, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x3b, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48,
	0x00, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x08, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4c, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x75, 0x2d, 0x4d, 0x52, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bussines_proto_rawDescOnce sync.Once
	file_bussines_proto_rawDescData = file_bussines_proto_rawDesc
)

func file_bussines_proto_rawDescGZIP() []byte {
	file_bussines_proto_rawDescOnce.Do(func() {
		file_bussines_proto_rawDescData = protoimpl.X.CompressGZIP(file_bussines_proto_rawDescData)
	})
	return file_bussines_proto_rawDescData
}

var file_bussines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bussines_proto_goTypes = []interface{}{
	(*Bussines)(nil),            // 0: pb.Bussines
	(*CreateBusssinesReq)(nil),  // 1: pb.CreateBusssinesReq
	(*BussinesRes)(nil),         // 2: pb.BussinesRes
	(*BranchOffice)(nil),        // 3: pb.BranchOffice
	(*Service)(nil),             // 4: pb.Service
	(*Product)(nil),             // 5: pb.Product
	(*Employee)(nil),            // 6: pb.Employee
	(*timestamp.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_bussines_proto_depIdxs = []int32{
	3, // 0: pb.Bussines.offices:type_name -> pb.BranchOffice
	4, // 1: pb.Bussines.services:type_name -> pb.Service
	5, // 2: pb.Bussines.products:type_name -> pb.Product
	5, // 3: pb.Bussines.warehouse:type_name -> pb.Product
	6, // 4: pb.Bussines.employees:type_name -> pb.Employee
	7, // 5: pb.BussinesRes.created_at:type_name -> google.protobuf.Timestamp
	1, // 6: pb.BussinesService.CreateBussines:input_type -> pb.CreateBusssinesReq
	2, // 7: pb.BussinesService.CreateBussines:output_type -> pb.BussinesRes
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bussines_proto_init() }
func file_bussines_proto_init() {
	if File_bussines_proto != nil {
		return
	}
	file_branch_office_proto_init()
	file_service_proto_init()
	file_product_proto_init()
	file_employee_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bussines_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bussines); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bussines_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBusssinesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bussines_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BussinesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bussines_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BussinesRes_CreatedAt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bussines_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bussines_proto_goTypes,
		DependencyIndexes: file_bussines_proto_depIdxs,
		MessageInfos:      file_bussines_proto_msgTypes,
	}.Build()
	File_bussines_proto = out.File
	file_bussines_proto_rawDesc = nil
	file_bussines_proto_goTypes = nil
	file_bussines_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BussinesServiceClient is the client API for BussinesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BussinesServiceClient interface {
	CreateBussines(ctx context.Context, in *CreateBusssinesReq, opts ...grpc.CallOption) (*BussinesRes, error)
}

type bussinesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBussinesServiceClient(cc grpc.ClientConnInterface) BussinesServiceClient {
	return &bussinesServiceClient{cc}
}

func (c *bussinesServiceClient) CreateBussines(ctx context.Context, in *CreateBusssinesReq, opts ...grpc.CallOption) (*BussinesRes, error) {
	out := new(BussinesRes)
	err := c.cc.Invoke(ctx, "/pb.BussinesService/CreateBussines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BussinesServiceServer is the server API for BussinesService service.
type BussinesServiceServer interface {
	CreateBussines(context.Context, *CreateBusssinesReq) (*BussinesRes, error)
}

// UnimplementedBussinesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBussinesServiceServer struct {
}

func (*UnimplementedBussinesServiceServer) CreateBussines(context.Context, *CreateBusssinesReq) (*BussinesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBussines not implemented")
}

func RegisterBussinesServiceServer(s *grpc.Server, srv BussinesServiceServer) {
	s.RegisterService(&_BussinesService_serviceDesc, srv)
}

func _BussinesService_CreateBussines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusssinesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BussinesServiceServer).CreateBussines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BussinesService/CreateBussines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BussinesServiceServer).CreateBussines(ctx, req.(*CreateBusssinesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BussinesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BussinesService",
	HandlerType: (*BussinesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBussines",
			Handler:    _BussinesService_CreateBussines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bussines.proto",
}
