// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: promotion.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Promotion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string       `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Porcentage  int32        `protobuf:"varint,2,opt,name=porcentage,proto3" json:"porcentage,omitempty"`
	ValidOn     string       `protobuf:"bytes,3,opt,name=valid_on,json=validOn,proto3" json:"valid_on,omitempty"`
	Conditions  []*Condition `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Types that are assignable to Type:
	//	*Promotion_Products
	//	*Promotion_Services
	Type isPromotion_Type `protobuf_oneof:"type"`
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promotion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *Promotion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Promotion) GetPorcentage() int32 {
	if x != nil {
		return x.Porcentage
	}
	return 0
}

func (x *Promotion) GetValidOn() string {
	if x != nil {
		return x.ValidOn
	}
	return ""
}

func (x *Promotion) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (m *Promotion) GetType() isPromotion_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Promotion) GetProducts() *Product {
	if x, ok := x.GetType().(*Promotion_Products); ok {
		return x.Products
	}
	return nil
}

func (x *Promotion) GetServices() *Service {
	if x, ok := x.GetType().(*Promotion_Services); ok {
		return x.Services
	}
	return nil
}

type isPromotion_Type interface {
	isPromotion_Type()
}

type Promotion_Products struct {
	//TODO:watch for the repeated tag
	Products *Product `protobuf:"bytes,5,opt,name=products,proto3,oneof"`
}

type Promotion_Services struct {
	Services *Service `protobuf:"bytes,6,opt,name=services,proto3,oneof"`
}

func (*Promotion_Products) isPromotion_Type() {}

func (*Promotion_Services) isPromotion_Type() {}

var File_promotion_proto protoreflect.FileDescriptor

var file_promotion_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4f, 0x6e, 0x12,
	0x2d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x21, 0x5a, 0x1f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x75, 0x2d, 0x4d,
	0x52, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_promotion_proto_rawDescOnce sync.Once
	file_promotion_proto_rawDescData = file_promotion_proto_rawDesc
)

func file_promotion_proto_rawDescGZIP() []byte {
	file_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(file_promotion_proto_rawDescData)
	})
	return file_promotion_proto_rawDescData
}

var file_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_promotion_proto_goTypes = []interface{}{
	(*Promotion)(nil), // 0: pb.Promotion
	(*Condition)(nil), // 1: pb.Condition
	(*Product)(nil),   // 2: pb.Product
	(*Service)(nil),   // 3: pb.Service
}
var file_promotion_proto_depIdxs = []int32{
	1, // 0: pb.Promotion.conditions:type_name -> pb.Condition
	2, // 1: pb.Promotion.products:type_name -> pb.Product
	3, // 2: pb.Promotion.services:type_name -> pb.Service
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_promotion_proto_init() }
func file_promotion_proto_init() {
	if File_promotion_proto != nil {
		return
	}
	file_condition_proto_init()
	file_service_proto_init()
	file_product_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_promotion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Promotion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_promotion_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Promotion_Products)(nil),
		(*Promotion_Services)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_promotion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_proto_msgTypes,
	}.Build()
	File_promotion_proto = out.File
	file_promotion_proto_rawDesc = nil
	file_promotion_proto_goTypes = nil
	file_promotion_proto_depIdxs = nil
}
